org.gradle.daemon=true
org.gradle.caching=true
org.gradle.parallel=false
org.gradle.workers.max=1
org.gradle.jvmargs=-Xmx512m -Xms128m -Dfile.encoding=UTF-8
android.aapt2FromMavenOverride=/data/user/0/com.itsaky.androidide/files/home/.androidide/aapt2
android.useAndroidX=true
android.enableJetifier=true
