org.gradle.daemon=true
org.gradle.caching=true
org.gradle.parallel=false
org.gradle.workers.max=1
org.gradle.jvmargs=-Xmx512m -Xms128m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.aapt2FromMavenOverride=/data/data/com.itsaky.androidide/files/home/android-sdk/build-tools/34.0.4/aapt2
